### ISSUE TITLE
Review Data binding approach in GeoExt3 Components

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#104]
There is a sample GeoExt application at https://github.com/geographika/geoext-demo-app

There are several components that could benefit from allowing data binding. E.g. 

- Allow Geoext.demo.app.view.Map to use a ViewModel for layers and map?
- See https://github.com/geoext/geoext3/pull/530 (otherwise the following error occurs - `Ext.mixin.Bindable.applyBind(): Cannot bind map on GeoExt.form.field.GeocoderComboBox - missing a setMap method.`
- https://github.com/geographika/geoext-demo-app/blob/master/app/view/grid/Grid.js#L38

**Comment by ahennr** [comment]
After some investigation, @chrismayer and me got following insights:

* In order to use map component or any other variable in binding, is has to be defined in `config`
* Generally spoken: variables defined for data-binding cannot be used in `initComponent` since binding is not yet performed at this point.
  * e.g. `locationLayerStyle` in `GeocoderComboBox` cannot be bound
* `get` / `apply` / `set`: As soon as `config` is used, before-mentioned methods are generated automatically by Ext.
  For all variables defined in the config object of a class these methods have to be overwritten if there is depending code logic for the certain variable.
  As an example, if a layer should be added to the map bound by view model, this has to be done in the `applyMap`:
```
applyMap: function (map) {
    var me = this;
    if (me.locationLayer) {
        map.addLayer(me.locationLayer);
    }
    return map; // => passed to setMap() => accessible via getMap()
}
```
* In contrast, with the MVC approach this would be possible in the `initComponent` directly. Thus, to support both mechanisms the code to add the `locationLayer` in the example has to be called in the `initComponent` as well, in particular by:
```
if (me.getMap()) {
    me.getMap().addLayer(me.locationLayer);
}
```
* If you want to support all configs by the MVVM bind mechanism this would bloat the (GeoExt) code a lot, especially for nested objects with other dependencies.
  * The deeper nested the dependencies are the more complex the corresponding methods `apply` and `set` will be.
* In most GeoExt components, binding of map component ("top-level object") can be done as long as the map is not used in `initComponent` or it's taken into consideration that it might be bound later.
* Since we do not want to loose backward compatibility for GeoExt we have to keep the MVC approach in our opinion and add MVVM binding where it makes sense in future components.

**Comment by geographika** [comment]
@ahennr - thanks for the summary. Something for future versions of GeoExt.
