### ISSUE TITLE
Layer Configuration Changes

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#243]
Layer configuration is done via the following 2 files:

1. https://github.com/compassinformatics/cpsi-mapview/blob/master/resources/data/layers/default.json
2. https://github.com/compassinformatics/cpsi-mapview/blob/master/resources/data/layers/tree.json

tree.json is used to provide structure to the layer tree, and layers are configured in default.json. 

It is proposed that the configuration is split into layer config and layer "view" - similar to the ExtJS Model/View approach. Currently some elements related to display are stored in default.json - it is proposed any "view" elements are moved to tree.json: 

- iconCls
- text
- qtip

As these are all properties of [Node Interface](https://docs.sencha.com/extjs/6.2.0/classic/Ext.data.NodeInterface.html) it may be simplest to use `Ext.apply` to set any of the NodeInterface  options so all settings could be applied from tree.json. 

An important feature would be to apply the [expanded](https://docs.sencha.com/extjs/6.2.0/classic/Ext.data.NodeInterface.html#cfg-expanded) property to a folder to have it closed/expanded on start-up and also the [checked](https://docs.sencha.com/extjs/6.2.0/classic/Ext.data.NodeInterface.html#cfg-checked) property to hide/show a checkbox at the folder level, so hiding/showing all the child layers can be disabled if required. 

![image](https://user-images.githubusercontent.com/490840/87310186-e8e0ee00-c51d-11ea-972b-3360c347efcb.png)

**Comment by chrismayer** [comment]
I opened a PR tacking most of the points. 

Setting`"checked": false` to hide checkbox fields in front of the tree nodes does not work since GeoExt [applies checked to the layer's visibility](https://github.com/geoext/geoext3/blob/master/src/data/model/LayerTreeNode.js#L82). Every non `null` / `undefined` value for `"checked" will force the rendering of the checkbox. 
It would be possible to hide the checkbox to hide the checkbox via CSS based on a config property as a workaround. What do you think @geographika ?

**Comment by geographika** [comment]
> It would be possible to hide the checkbox to hide the checkbox via CSS based on a config property as a workaround. What do you think @geographika ?

This approach sounds fine to me. It is mainly to stop users checking a box with lots of layers underneath and affecting performance.
