### ISSUE TITLE
WMS GetFeatureInfo Tool

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#251]
Create a new Information Tool allowing users to click on features on the map and return attribute information. 
This would be similar to old GeoExt functionality such as that outlined in:

https://girona-geoext-workshop.readthedocs.io/en/latest/stores/getfeatureinfo.html

![image](https://user-images.githubusercontent.com/490840/87533431-e3f27a80-c694-11ea-8531-29af3fb429c3.png)

Possibly relevant code in the [BasiGX.plugin.Hover](http://terrestris.github.io/BasiGX/master/docs/#!/api/BasiGX.plugin.Hover-method-getFeatureInfoCount) tool. 

For WMS layers the GetFeatureInfo protocol will be used to return data in GeoJSON format. Example URLs will be added to this issue. 

To discuss:

- Expand top layer by default?
- Combine with vector features in the same location? Leave for future phase.

**Comment by simonseyock** [comment]
@geographika Is it somehow possible that you can provide urls to publicly available WMS instances that will return feature info in geojson format? 2 different ones would be nice.

**Comment by geographika** [comment]
@simonseyock:

I have setup the Boreholes and waterbodies WMS used in the demo app to return GeoJSON:

![image](https://user-images.githubusercontent.com/490840/94799630-b4c1ee80-03e3-11eb-9532-9e3349dd84ea.png)

Sample waterbodies request:

https://w08-mapserver.compass.ie/mapserver/?map=/MapServer/apps/mapview-demo/example.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=waterbodies&LAYERS=waterbodies&INFO_FORMAT=geojson&I=50&J=50&CRS=EPSG%3A3857&STYLES=&WIDTH=101&HEIGHT=101&BBOX=-1020457.977140593%2C7043518.784430502%2C-1008115.2011426362%2C7055861.560428459

Sample Boreholes request (although no features at location - tricky trying to get this right manually!):

![image](https://user-images.githubusercontent.com/490840/94799169-01f19080-03e3-11eb-8a70-ba2d15c1693b.png)

https://w08-mapserver.compass.ie/mapserver/?map=/MapServer/apps/mapview-demo/example.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&FORMAT=image%2Fpng&TRANSPARENT=true&QUERY_LAYERS=Boreholes&LAYERS=Boreholes&INFO_FORMAT=geojson&I=50&J=50&CRS=EPSG%3A3857&STYLES=&WIDTH=101&HEIGHT=101&BBOX=-1020457.977140593%2C7043518.784430502%2C-1008115.2011426362%2C7055861.560428459

**Comment by geographika** [comment]
All WMS layers at https://w08-mapserver.compass.ie/mapserver/?map=/MapServer/apps/mapview-demo/example.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities should now be configured to return GeoJSON as part of a WMS GetFeatureInfo request.

**Comment by simonseyock** [comment]
With this issue I am running into a problem with openlayers. If I render ExtJs components inside an overlay the events get swallowed by openlayers because of the `stopevent-container`. This causes interactive elements like buttons in extjs not to work. This has been fixed by openlayers in v6.

The existing `geoext.Popup` component could then extend from Panel instead of Component and it could be easily reused.

If you want to see the problem in geoext, see this branch: https://github.com/simonseyock/geoext3/tree/popup-panel
(you can toggle the `stopEvent` property of the `ol.Overlay` in `src/component/Panel.js` to change the stop event behaviour)
If you want to see the problem in openlayers v4: https://codepen.io/simon_seyock/pen/YzWXJOP
aaand the problem does not exist in openlayers v6: https://codesandbox.io/s/festive-blackwell-w2np8

To use openlayers v6 we would need to update geoext, basigx and cpsi-mapview. At the moment I am looking into the changes that need to be done.
https://github.com/openlayers/openlayers/releases/tag/v5.0.0
https://github.com/openlayers/openlayers/releases/tag/v6.0.0
Most of the changes are simply renamings or contain code snippets on how to maintain the old behaviour. These will be pretty easy. The only thing that I think is a little more work is the overview map - it can no longer show all parent layers but needs it's own layers.

**Comment by simonseyock** [comment]
After discussing this issue I think the work that is required will take from 2 to 3 days. I think this is too much for this code sprint.

I opened an issue and a PR on the geoext repository to kick-start the discussion: https://github.com/geoext/geoext3/issues/652

Alternative options are:
1. Manually wire up the events. This could cause unexpected errors and needs to be respected if the component should get extended
2. Display a free floating window and mark the clicked position on the map

I would prefer the second option as it will be easier to maintain and will result in cleaner code.

**Comment by simonseyock** [comment]
The second option will also be the easiest to implement and we will probably not need much more than what we calculated.

**Comment by geographika** [comment]
@simonseyock - the floating window sounds fine to me, along with a clicked marker. 

Updating GeoExt to OL6 is very much of interest for a future sprint or joint codesprint.

**Comment by simonseyock** [comment]
@geographika the server returns a feature collection. Will there ever be more than one feature in the feature info response?

**Comment by geographika** [comment]
Yes there could be - for example two roads crossing each other.
