### ISSUE TITLE
Performance Issues with Layer Tree Legends

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#274]
When a layer's visibility changes the UI hangs briefly, the layer tree disappears and is then redrawn. When there are lots of layers this can take 1s or more to complete, and delays other UI actions (e.g. a form being hidden). 

## Possible Cause

The initial trigger is any part of the application changing the layer visibility - in GeoExt the LayerTreeNode - onLayerVisibleChange is called. 

In the mapview project `getLegendHtml` is called for every layer in the tree.

https://github.com/compassinformatics/cpsi-mapview/blob/1d3687e678e0ba62ea87d05ca051244dce3a4b02/app/plugin/BasicTreeColumnLegends.js#L48

The following always appear to be `undefined` and so `LegendUtil.createGetLegendGraphicUrl(layer)` is called (which I believe is taking the time).

```
var legendUrl = layer.get('legendUrl');
var w = layer.get('legendWidth');
var h = layer.get('legendHeight');
```

Maybe these should be set on the first calculation, so they are cached?
However there are several other plugins used in the LayerTree that may be the cause. 

https://github.com/compassinformatics/cpsi-mapview/blob/1d3687e678e0ba62ea87d05ca051244dce3a4b02/app/view/LayerTree.js#L37

**Comment by chrismayer** [comment]
With regard to the [comment](https://github.com/compassinformatics/cpsi-mapview/pull/284#issuecomment-701591173) of @geographika:

Yes it seems that the complete tree is re-rendered in case a property (mostly visibility of a layer) gets changed. Due to my reaserch it is even worse since the `getLegendHtml` function of the `CpsiMapview.plugin.BasicTreeColumnLegends` is called several (~6) times in case one layer is set visible / invisible. Maybe it is related to cascading down the whole tree structure due to `toggleParentNodes` as suggested in your comment. I can dig deeper into this, but I am not sure if we can get around this.

**Comment by geographika** [comment]
@chrismayer - if you can find out why the full tree is redrawn that would help to decide what to do. On testing a normal treepanel it should not need to refresh all nodes when the backing store is updated. 
The full refresh also causes #287

**Comment by chrismayer** [comment]
Did some more investigations on this:

It seems that some of the tree plugins cause the full redrawing of the tree. It seems that either `cmv_basic_tree_column_legend` or `cmv_tree_column_style_switcher` (or maybe both) are responsible for this. Or better said the tree's [view](https://docs.sencha.com/extjs/6.2.0/classic/Ext.view.Table.html) is refreshed on every action like (checking a node), but rendering the sub-elements such as legend and style-switcher every time causes the laggy behaviour of the tree.

@geographika Could you please test the follwoing scenarios in your apps with many layers:

- Removing  both `cmv_basic_tree_column_legend` and `cmv_tree_column_style_switcher` (comment out [here](https://github.com/compassinformatics/cpsi-mapview/blob/master/app/view/LayerTree.js#L38)) and test in app with many layers, if the tree behaves "normal"
- Removing only `cmv_basic_tree_column_legend` and test in app with many layers
- Removing only `cmv_tree_column_style_switcher` and test in app with many layers

I have the feeling that `cmv_tree_column_style_switcher` could be the bad one since it adds quite heavy components to the tree node and needs a lot of deleting and re-creation of components on every refresh.

**Comment by geographika** [comment]
@chrismayer - yes removing both of these plugins avoids a full redraw of the tree, and the "jumping" effect mentioned in #287 
The performance is better now that folders can be started collapsed (previously all nodes were displayed when the application started). 
The `cmv_tree_column_style_switcher` seems to have a slightly bigger effect on performance. 

The layer tree is fully refreshed when any layer that is part of the tree changes visibility. 

I think my change in #263 could be one of the causes of this.

**Comment by geographika** [comment]
I can't seem to work out why `cmv_basic_tree_column_legend` would cause a full tree refresh though.

**Comment by geographika** [comment]
With the following changes performance is now acceptable:

- https://github.com/compassinformatics/cpsi-mapview/pull/302
- https://github.com/compassinformatics/cpsi-mapview/pull/289 (allowing collapsed nodes at start-up)
- If implemented - https://github.com/compassinformatics/cpsi-mapview/issues/304 will cause less refreshes
- https://github.com/compassinformatics/cpsi-mapview/pull/284 will also reduce requests

For reference:

> there is no possibility to directly render ExtJS components under a tree node (this has been possible in previous versions). 

The tree jumping issue #287 however remains an issue.
