### ISSUE TITLE
Implement WFS Paging for Feature Grids

### ISSUE THREAD

**Issue by geographika** [compassinformatics/cpsi-mapview#95]
Building on the https://github.com/geoext/geoext3/blob/master/src/util/OGCFilter.js it would be good to also implement paging to work with the https://docs.sencha.com/extjs/6.5.1/classic/Ext.toolbar.Paging.html

This would allow a grid to be filled with features via a WFS service and paged through (whilst also having a "twin" WMS layer showing all features / or filtered features). 

MapServer implements paging for WFS 1.1.0 as a custom extension (using STARTINDEX and MAXFEATURES), and WFS 2 using the standard STARTINDEX and COUNT/ 

https://mapserver.org/development/rfc/ms-rfc-105.html#response-paging-support

Geoserver also implements the WFS 2 standards for paging.

**Comment by chrismayer** [comment]
I did a prototype for a WFS Paging Toolbar, which can be seen here: https://github.com/chrismayer/geoext3/blob/wfs-paging/src/toolbar/WfsPaging.js

Example using it: https://github.com/chrismayer/geoext3/blob/wfs-paging/examples/features/grid-paging.js

The approach has some assumptions / restrictions, which I want to make transparent and discuss with you before I go on with that:

The paging toolbar needs to manipulate the WFS request send by the vector source of the OL layer. 
Since the [ol.source.Vector](https://openlayers.org/en/v4.6.5/apidoc/ol.source.Vector.html) class of OpenLayers does not have a `setUrl` function we need to manipulate the URL for loading the features by WFS with paging by some other way. In the current prototype I decided to rely on member variables `sortBy`, `startIndex`, `count` on the layer instance, which have to be set by the developer using the toolbar. These member vars are used in the `url` function of the source to assemble the WFS request. By manipulating them the toolbar can influence the WFS request. So this approach is limited to:

* `sortBy`, `startIndex`, `count` must be set on the WFS layer
*  Only WFS layers with vector sources configured with `url` configs can be used by this. Those with custom loader function wouldn't

Another possibility would be to inject a custom loader function to the vector source. But it feels a bit aggressive to manipulate the source like that.

Any ideas / opinions on this? Especially regarding the point is this something for GeoExt or is it not generic enough? Maybe something for BasiGX or just for CPSI-Mapview? TIA!

/cc @marcjansen @weskamm @geographika

**Comment by weskamm** [comment]
I think the approach is good, i also see no real option to handle sources with a loader function.
So its ok to restrict the paging to vector layers / sources that have just a plain url instead of a loader.
Other options that comes to my mind could be to create a new loading strategy in openlayers (WFS with paging) or a new ExtJS proxy which is bound to the store, but this are just ideas, not sure how if this really can work out.

Placing the code in GeoExt is ok to me as it fits well!

**Comment by chrismayer** [comment]
Thanks a lot for your feedback @weskamm!
I agree that there will be no real chance to master `loader`-based vector sources. So I am fine if we restrict it to `url`-based vector sources.
What concerns me more is the fact that in the approach the OL layer has to be created in a specific way, which could bring some potential of errors in case the dev does not fulfil them.
Maybe turning things around and offering a `WfsFeatureStore` which takes care of loading the features by a WFS and puts them into a vector layer (I guess the same what you meant by "a new ExtJS proxy which is bound to the store" in your comment?). But this is totally a paradigm change since until now all GX stores handle local OL objects, which were already loaded from somewhere else.

**Comment by chrismayer** [comment]
I implemented a specific "WFS FeatureStore", which loads the features itself from the WFS. This has less assumptions, thus it is much cleaner and the toolbar also fits in way better than before (90% default behaviour of ExtJS `PagingToolbar`).

You can have a look here: https://github.com/geoext/geoext3/pull/517

**Comment by chrismayer** [comment]
The PR in the GeoExt repo (https://github.com/geoext/geoext3/pull/517) is now ready for reviews. TIA!

**Comment by geographika** [comment]
@chrismayer - the demo example is excellent. This along with the filters will allow a fully WMS/WFS driven grid/map application. 

I'm trying to now set this up as part of a larger application - creating a GeoExt.data.store.WfsFeatures store, and a grid, and binding the two together in a grid panel with a view model:

```
    extend: 'Ext.grid.Panel',
..
    xtype: 'featuregrid',
..
    bind: {
        store: '{featuresummary}'
    },
    bbar: {
        // WFS paging toolbar
        xtype: 'gx_wfspaging_toolbar',
        displayInfo: true
    }
```

I'm using the same service as the demo, and same store definition. The features load fine into the grid but the paging toolbar is disabled. Are there any extra steps that need to be done when binding a store from a ViewModel?
I've tried also binding to the store in the bbar but no luck.

**Comment by chrismayer** [comment]
Hmm, the only thing happening in the `WfsPagingToolbar` is to ensure the `onLoad` function is called once the store is ready (event `gx-wfsstoreload`). See [here](https://github.com/geoext/geoext3/pull/517/files#diff-c87858fb352ee928995c3d8d24a8d782R46). 

Could you try to modify the the line mentioned above to:

```javascript
// use me.getStore() instead of me.store
me.getStore().on('gx-wfsstoreload', me.onLoad, me);
// ensure the event is fired
me.getStore().on('gx-wfsstoreload', function() {console.log('wfsstoreload fired' )});

```

**Comment by geographika** [comment]
Thanks for the tip. There is no output to the console. It looks like the store is still "ext-empty-store" when onAddedToParent is called, and then the binding sets the Wfs store later. The paging class has a storeChanged event so I'll try seeing the listener again with this.

**Comment by geographika** [comment]
I now have it working by hacking the WfsPaging.js file as follows:

```
    onAddedToParent: function(pager, container) {
        var store = container.getViewModel().getStore('featuresummary');
        store.on('gx-wfsstoreload', function () {
            me.onLoad();
        });
    }
```
Obviously this isn't a generic solution, and would be better in the controller, but I'm guessing there is some store change event somewhere I'm missing which would solve this.

**Comment by chrismayer** [comment]
Thanks for sharing your solution @geographika.

Maybe additionally overwriting `onOwnerStoreChange` of the toolbar does have any effect? Untested since I do not have your setup at the moment.

```javascript
    onOwnerStoreChange: function(owner, store) {
        var me = this;
        me.callParent(arguments);
        me.store.on('gx-wfsstoreload', me.onLoad, me);
    },
```

**Comment by geographika** [comment]
@chrismayer - perfect! That did the trick. I think binding stores to grids using view models is a fairly standard approach, so does it make sense to add this function to the class?

**Comment by geographika** [comment]
One further question. The demo has the WFS store sorted by NAME (with the sortBy property). This currently sorts the features locally (so only the 10 features loaded in the grid). 
To allow server-side sorting I can set ``remoteSort: true`` however this currently doesn't have an effect. 
Is WFS sorting implemented in the WFStore or is this something for a future update?

**Comment by chrismayer** [comment]
> I think binding stores to grids using view models is a fairly standard approach, so does it make sense to add this function to the class?

Sure makes totally sense. I added the fix in https://github.com/geoext/geoext3/pull/517/commits/12ec8f1c69aecf6300e297621404d2f550a82f67

**Comment by chrismayer** [comment]
> Is WFS sorting implemented in the WFStore or is this something for a future update?

I not 100% sure what's happening in detail, but I guess this something for a future update.

**Comment by geographika** [comment]
Tested/integrated. Some issues on the back-end to resolve (it appears the MapServer SQL Server driver currently has no sortBy support), but the paging feature works great.
