### ISSUE TITLE
NumericAttributeSlider: detect actual field to use from layer, not (only?) from configuration

### ISSUE THREAD

**Issue by marcjansen** [compassinformatics/cpsi-mapview#99]
Right now the `NumericAttributeSlider` is configured with a `numericField` so that all layers that are attribute filterable (having a config `numericitem`) will receive a filter with that particular field.

We think it might make more sense to have the information about the actual field be stored at the layer not at the slider:

```js
var layerConfigA = {
    // …
    numericitem: 'myActualFieldName'
};
var layerConfigB = {
    // …
    numericitem: 'someOtherFieldname'
};
var layerConfigB = {
    // …
    numericitem: 'thisNeverGetsSilly'
}
```

One slider could then produce a valid filter for both of the layers.

We might also have a combination, where a slider would tell us which types of fields it will affect and the layers know which fields they have. This way an application is imagineable in which there are n-sliders (with different ranges) and a bunch of layers and all sorts of intersection effects are possible:

```js
// pseudocode
var slider1 = Ext.create('NumericAttributeSlider', {
    affects: [
        'myActualFieldName',
        'thisNeverGetsSilly' // these have the same range but different semantics
    ]
});

var slider2 = Ext.create('NumericAttributeSlider', {
    affects: [
        'someOtherFieldname' //different range and different semantics
    ]
});

var layerConfigA = {
    // notice the plural and that this an array now
    numericitems: [ 'myActualFieldName', 'someOtherFieldname']
    // => will be affected by both sliders
};
var layerConfigB = {
    numericitems: ['someOtherFieldname']
    // => will be affected by slider2 only
};
var layerConfigB = {
    // …
    numericitems: [ 'myActualFieldName', 'thisNeverGetsSilly']
    // => will be affected by slidera only but with a combined filter
}
```

This is open to discussion, see [also here](https://github.com/meggsimum/cpsi-mapview/pull/94/files/fa549371305c378e55f923271b8f848eecf34cf9#r288407195).

We should decide what we want and estimate accordingly.

**Comment by geographika** [comment]
Sorry for the delay in getting round to reviewing this. 
I've integrated the current slider into a full application and it works well. 

Maybe the slider should accept a config based on an array of layers and a field property and bypass setting in the factory/config altogether? 

The http://terrestris.github.io/BasiGX/master/docs/#!/api/BasiGX.util.Layer-static-method-getLayerBy looks like it would be easy to get a list of affected WFS/vector layers to pass into a config. 
An array of layer/field configs would be even more flexible. 

From a UI perspective the slider seems to fit well into a grid (in the bbar) based on a WfsStore rather than a more global slider at the bottom of the map (rather than the original approach which was based on the timeslider which made more sense when filtering multiple layers). 

Does the above approach make sense / have any merits?
```javascript

var myLayers = BasiGX.util.Layer.getLayerByFeatureType(); // get all WFS layers by a ol key?

var slider1 = Ext.create('NumericAttributeSlider', {
     numericField: 'myField',
     affects: myLayers
});

// alternative?

var slider2 = Ext.create('NumericAttributeSlider', {
     affects: [
        {layer: layer1, numericField 'field1'}, 
        {layer: layer2, numericField 'field2'} 
];

```
});

**Comment by marcjansen** [comment]
That doesn't sound so bad at first read. I try to see what the above would mean codewise. Thanks for the feedback

**Comment by geographika** [comment]
Closing as functionality is fine as-is.
